name: welch_psd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # fftea: ^1.5.0
  # complex: ^0.7.2
  # tuple: ^2.0.2
  scidart: ^0.0.2-dev.12

flutter:
  uses-material-design: true

  assets:
  - assets/440_with_noise_8000hz.txt